### ISSUE TITLE
Unable to build on UBUNTU AMD 64 with GO1.5.2.

### ISSUE THREAD

**Issue by panbhatt** [Clever/moredis#12]
Hi  Team,
  Unable to build this project on UBUNTU  with GO1.5.2.

~/GOLANG/moredis$ gvm use go1.5.2
Now using version go1.5.2
~/GOLANG/moredis$ go version
go version go1.5.2 linux/amd64
~/GOLANG/moredis$ make
stat /home/pankaj/.gvm/pkgsets/go1.5.2/global/src/github.com/Clever/moredis/cmd/moredis*/**.go: no such file or directory
Makefile:34: recipe for target 'github.com/Clever/moredis/cmd/moredis' failed
make: *** [github.com/Clever/moredis/cmd/moredis] Error 2

Can someone help.

**Comment by dfuentes** [comment]
Dependencies for this project are managed via glide.  Could you try running `make install_deps` first?

**Comment by panbhatt** [comment]
I am not a GO PRO.. so just use GVM to install go1.5.2 .. i tried with make install_deps.. it also throws error.
pankaj@pankaj-VirtualBox:~/GOLANG/moredis$ make install_deps
Oops! Import gopkg.in/mgo.v2 repeated with different versions '' and '4d04138ffef2791c479c0c8bbffc30b34081b8d9'
Makefile:70: recipe for target 'install_deps' failed
make: *** [install_deps] Error 1

**Comment by dfuentes** [comment]
Oops, I've cleared up that import issue, could you pull latest?

Sorry, I don't use gvm, could you give the output of: `echo $GOPATH`?

The repo should be checked out to `$(GOPATH)/src/github.com/Clever/moredis`

**Comment by panbhatt** [comment]
This is the output of the variable 
/home/pankaj/.gvm/pkgsets/go1.5.2/global

**Comment by panbhatt** [comment]
after doing a fresh pull "make install_deps" works fine, however the maek still gives the same error.

**Comment by dfuentes** [comment]
Yeah, I think it's because it's expecting the normal go conventions for file paths.  Did you get this repo by cloning or via `go get`?

**Comment by panbhatt** [comment]
Sure, will try and provide you the results... soon.. .thanks a lot for helping.
